model:
    residual: true
    depth: 4
    filter_growth: 48
    disc_filters: 48

training:
    batch_size: 6
    learning_rate: 0.0002
    epochs: 50
    decay_epoch: 3
    beta1: 0.5
    id_lambda: 0.5
    cycle_lambda: 5.0
    ssim_lambda: 0.0